/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TramaRouteImport } from './routes/trama'
import { Route as TematicheRouteImport } from './routes/tematiche'
import { Route as PersonaggiRouteImport } from './routes/personaggi'
import { Route as HistoryWalkRouteImport } from './routes/history-walk'
import { Route as EdizioniRouteImport } from './routes/edizioni'
import { Route as BiografiaRouteImport } from './routes/biografia'
import { Route as IndexRouteImport } from './routes/index'

const TramaRoute = TramaRouteImport.update({
  id: '/trama',
  path: '/trama',
  getParentRoute: () => rootRouteImport,
} as any)
const TematicheRoute = TematicheRouteImport.update({
  id: '/tematiche',
  path: '/tematiche',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaggiRoute = PersonaggiRouteImport.update({
  id: '/personaggi',
  path: '/personaggi',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryWalkRoute = HistoryWalkRouteImport.update({
  id: '/history-walk',
  path: '/history-walk',
  getParentRoute: () => rootRouteImport,
} as any)
const EdizioniRoute = EdizioniRouteImport.update({
  id: '/edizioni',
  path: '/edizioni',
  getParentRoute: () => rootRouteImport,
} as any)
const BiografiaRoute = BiografiaRouteImport.update({
  id: '/biografia',
  path: '/biografia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biografia': typeof BiografiaRoute
  '/edizioni': typeof EdizioniRoute
  '/history-walk': typeof HistoryWalkRoute
  '/personaggi': typeof PersonaggiRoute
  '/tematiche': typeof TematicheRoute
  '/trama': typeof TramaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biografia': typeof BiografiaRoute
  '/edizioni': typeof EdizioniRoute
  '/history-walk': typeof HistoryWalkRoute
  '/personaggi': typeof PersonaggiRoute
  '/tematiche': typeof TematicheRoute
  '/trama': typeof TramaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biografia': typeof BiografiaRoute
  '/edizioni': typeof EdizioniRoute
  '/history-walk': typeof HistoryWalkRoute
  '/personaggi': typeof PersonaggiRoute
  '/tematiche': typeof TematicheRoute
  '/trama': typeof TramaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biografia'
    | '/edizioni'
    | '/history-walk'
    | '/personaggi'
    | '/tematiche'
    | '/trama'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biografia'
    | '/edizioni'
    | '/history-walk'
    | '/personaggi'
    | '/tematiche'
    | '/trama'
  id:
    | '__root__'
    | '/'
    | '/biografia'
    | '/edizioni'
    | '/history-walk'
    | '/personaggi'
    | '/tematiche'
    | '/trama'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiografiaRoute: typeof BiografiaRoute
  EdizioniRoute: typeof EdizioniRoute
  HistoryWalkRoute: typeof HistoryWalkRoute
  PersonaggiRoute: typeof PersonaggiRoute
  TematicheRoute: typeof TematicheRoute
  TramaRoute: typeof TramaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trama': {
      id: '/trama'
      path: '/trama'
      fullPath: '/trama'
      preLoaderRoute: typeof TramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tematiche': {
      id: '/tematiche'
      path: '/tematiche'
      fullPath: '/tematiche'
      preLoaderRoute: typeof TematicheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personaggi': {
      id: '/personaggi'
      path: '/personaggi'
      fullPath: '/personaggi'
      preLoaderRoute: typeof PersonaggiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history-walk': {
      id: '/history-walk'
      path: '/history-walk'
      fullPath: '/history-walk'
      preLoaderRoute: typeof HistoryWalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edizioni': {
      id: '/edizioni'
      path: '/edizioni'
      fullPath: '/edizioni'
      preLoaderRoute: typeof EdizioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biografia': {
      id: '/biografia'
      path: '/biografia'
      fullPath: '/biografia'
      preLoaderRoute: typeof BiografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiografiaRoute: BiografiaRoute,
  EdizioniRoute: EdizioniRoute,
  HistoryWalkRoute: HistoryWalkRoute,
  PersonaggiRoute: PersonaggiRoute,
  TematicheRoute: TematicheRoute,
  TramaRoute: TramaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
